spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:/sql/dishbrary-schema.sql
  jpa:
    hibernate:
      ddl-auto: none


dishbrary:
  init:
    security: true
    ingredients: true
    cuisines: true
    categories: true
    generateMockData: true
  ingredients:
    images:
      default:
        name: default.png
  cuisine:
    images:
      default:
        name: default.png
  recipe:
    images:
      defaultCoverImage:
        name: default-recipe-cover-image.png
  resources:
    imageBasePathByComponentName:
      user: /home/znato/work/szakdolgozat/dishbrary-assets/
      cuisine: /home/znato/work/szakdolgozat/dishbrary/cuisine_icons/
      ingredient: /path/to/ingredientImages/
      recipe: /home/znato/work/szakdolgozat/dishbrary-assets/