spring:
  jpa:
    hibernate:
      ddl-auto: none

cxf:
  path: /rest
  jaxrs:
    component-scan: true
    classes-scan-packages: hu.gdf.szgd.dishbrary.web.rest, com.fasterxml.jackson.jaxrs


dishbrary:
  init:
    security: false
    ingredients: false
    cuisines: false
    categories: false
    generateMockData: false
  ingredients:
    images:
      default:
        name: default.png
  cuisine:
    images:
      default:
        name: default.png
  recipe:
    images:
      defaultCoverImage:
        name: default-recipe-cover-image.png
  resources:
    imageBasePathByComponentName:
      user: /home/znato/work/szakdolgozat/dishbrary-assets/
      cuisine: /home/znato/work/szakdolgozat/dishbrary/cuisine_icons/
      ingredient: /path/to/ingredientImages/
      recipe: /home/znato/work/szakdolgozat/dishbrary-assets/

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/dishbrary
    username: dishbrary
    password: qwe123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

---

spring:
  profiles: dev, test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:/sql/dishbrary-schema.sql

dishbrary:
  init:
    security: true
    ingredients: true
    cuisines: true
    categories: true
    generateMockData: true

---

spring:
  profiles: demo
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:/sql/dishbrary-schema.sql

dishbrary:
  init:
    security: true
    ingredients: true
    cuisines: true
    categories: true
    generateMockData: true
  resources:
    imageBasePathByComponentName:
      user: ./dishbrary-assets/
      cuisine: ./cuisine_icons/
      recipe: ./dishbrary-assets/