spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver


dishbrary:
  init:
    ingredients: true
  ingredients:
    images:
      basepath: /todo/define/this
      default:
        location: /todo/define/this/too